# Generated by Django 3.2.9 on 2022-10-28 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('album_id', models.PositiveIntegerField(unique=True)),
                ('height', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('dominant_color_hex', models.CharField(default='#ffffff', max_length=7)),
                ('url', models.FileField(max_length=254, upload_to='photo')),
            ],
        ),
    ]
